name: Matrix
on:
  workflow_dispatch:

jobs:
  test:
    if: always()
    strategy:
      fail-fast: false
      matrix:
        node: [10, 12, 14, 16, 18]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v3
        with:
          key: "${{ hashFiles('package-lock.json') }}"
          path: node_modules
      - run: make install
      - run: make test

  test_fail_fast:
    if: always()
    strategy:
      fail-fast: true
      matrix:
        node: [10, 12, 14, 16, 18]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: "${{ hashFiles('package-lock.json') }}"
      - run: make install
      - run: make test

  test_multiple_os:
    if: always()
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [10, 14, 12, 16, 18]
        exclude:
          - node: 10
            os: ubuntu-latest
          - node: 12
            os: ubuntu-latest
          - node: 10
            os: windows-latest
          - node: 12
            os: windows-latest
        include:
          - node: 14
            os: ubuntu-22.04
          - node: 16
            os: ubuntu-22.04
          - node: 18
            os: ubuntu-22.04
          - node: 14
            os: windows-2019
          - node: 16
            os: windows-2019
          - node: 18
            os: windows-2019
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: "${{ hashFiles('package-lock.json') }}"
      - run: make install
      - run: make test
